#!/usr/bin/env bash
# word wide web

prints () {
    local domain="$1"
    local subdomain="$2"

    dig "$domain" | grep -A1 'ANSWER SECTION:' | sed -r "s/$domain/$subdomain/g" | awk -F" " 'NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain="www.$1"
    subdomain="www"
    prints "$domain" "$subdomain"
    
    domain="lb-01.$1"
    subdomain="lb-01"
    prints "$domain" "$subdomain"

    domain="web-01.$1"
    subdomain="web-01"
    prints "$domain" "$subdomain"

    domain="web-02.$1"
    subdomain="web-02"
    prints "$domain" "$subdomain"
elif [ $# -eq 2 ]; then
    domain="$2.$1"
    subdomain="$2"
    prints "$domain" "$subdomain"
fi

