#!/usr/bin/env bash

# Define subdomains to check
subdomains=('www' 'lb-01' 'web-01' 'web-02')

# Function to get information about a subdomain
get_subdomain_info() {
    local subdomain="$1"
    local domain="$2"

    local dig_result
    dig_result=$(dig "$subdomain.$domain" +short)

    if [ -n "$dig_result" ]; then
        local record_type
        record_type=$(dig "$subdomain.$domain" +short -t "$dig_result" | awk '{print $4}')
        echo "The subdomain $subdomain is a $record_type record and points to $dig_result"
    else
        echo "No DNS information found for $subdomain.$domain"
    fi
}

# Check the number of arguments
if [ $# -eq 1 ]; then
    domain="$1"
    for subdomain in "${subdomains[@]}"; do
        get_subdomain_info "$subdomain" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    sub="$2"
    get_subdomain_info "$sub" "$domain"
fi

