#!/bin/bash
# Check if the script was passed an argument

if [ $# -ne 1 ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

ip_address=$1

for i in {1..5}; do
  ping -c 1 $ip_address
done
