#!/bin/bash

# Replace port 8080 with port 80 in the Nginx default configuration
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

service nginx stop
truncate -s 0 /run/nginx.pid
service nginx start
