#!/usr/bin/env bash
# Function to delete the PID file and terminate the script

cleanup() {
    echo "Cleaning up..."
    rm -f /var/run/myscript.pid
    exit 0
}

trap cleanup SIGQUIT SIGTERM
trap 'echo "Y U no love me?"' SIGINT
echo $$ > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
done
