#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely.

while true
do
    echo "To infinity and beyond"
    sleep 2

    if [ $? -ne 0 ]; then
        echo "I am invincible!!!"
        break
    fi
done

