#!/usr/bin/env bash
# displays the content of the file /etc/passwd with a story.

while IFS=: read -r USERNAME PASSWORD USER_ID GROUP_ID USER_INFO HOME_DIR COMMAND _
do
    echo -n "The user $USERNAME is part of the $GROUP_ID gang, "
    echo -n "lives in $HOME_DIR and rides $COMMAND. "
    echo -n "$USER_ID's place is protected by the passcode $PASSWORD, "
    echo "more info about the user here: $USER_INFO"

done < "/etc/passwd"
