#!/usr/bin/env bash
# displays the visitor IP along with the HTTP status code,
# this is from  the Apache log file.

awk '{ printf "Visitor IP: %s, HTTP Status Code: %s\n", $1, $9 }' apache-access.log

