#!/usr/bin/env bash
# Configures an Ubuntu server to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8

# Create a backup of the hosts file.
cp /etc/hosts ~/hosts.new

# Update the hosts file.
echo "127.0.0.2 localhost" >> ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Replace the hosts file with the updated version.
cp ~/hosts.new /etc/hosts

