#!/usr/bin/env bash
# nginx as user listening on all active IPs on port 8080
pkill apache2
sed -i -e 's/#user www-data/user nginx/' -e 's/80/8080/' /etc/nginx/nginx.conf
sudo -u nginx nginx -c /etc/nginx/nginx.conf
