#!/usr/bin/env bash


# Change the user to nginx in the nginx.conf file
chmod -R 777 /etc/nginx/
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# Change the listening port to 8080 in the default site configuration
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Ensure correct permissions for nginx.conf
chmod 644 /etc/nginx/nginx.conf

# Stop Apache2 if it's running (it's not needed if using Nginx)
pkill apache2

# Start Nginx as the nginx user
sudo -u nginx nginx -c /etc/nginx/nginx.conf

